name: build-and-deploy

on:
  push:
    branches:
      - master  # 如果你用的是 main，请替换这里

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Fix openssl issue + remove node-sass
        run: |
          echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
          npm uninstall node-sass || true
          npm install sass

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
