name: build-and-deploy

on:
  push:
    branches:
      - master  # 或 main，根据你的默认分支而定

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies (use sass instead of node-sass)
        run: |
          npm uninstall node-sass || true
          npm install sass
          npm install

      - name: Build project
        run: npm run export || npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
